### ISSUE TITLE
contribution guide link is to a different project

### ISSUE THREAD

**Issue by caesar** [Akylas/mbview-rs#2]
The "contribution guide" link in the readme goes to `https://xplorer.space/docs/community/Contributing`. I'm not sure if this is intentional but, since there's no apparent relationship between the two projects, it would be better for this project to have its own contribution guide.

Thanks for the cool project by the way, I'm looking forward to contributing once I familiarise myself with the codebase! :-)

**Comment by farfromrefug** [comment]
@caesar thanks I actually copied their readme as a base ;)
