### ISSUE TITLE
Failed to start the project

### ISSUE THREAD

**Issue by pannz** [Akylas/mbview-rs#3]
### Description

Cloned the project and install the dependencies. I run `pnpm dev:web` successfully but when open the web, it will report `window.__TAURI_IPC__ is not a function` instantly in console. And when click the add another mbtiles file (extract from OSM, so the file itself is fine), there will be no response, and console will show `window.__TAURI_IPC__ is not a function` again.
Same when running `pnpm dev`, the macOS app appears but once click add another mbtiles, no response, and show following logs

```
2023-03-07 14:39:04.627 MBTilesViewer[77582:2463167] +[CATransaction synchronize] called within transaction
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/service.rs:118:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/service.rs:118:60
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/service.rs:118:60
🚀 A new version of Tauri CLI is available! [1.2.3]
```
And the `Tauri info`:
```
~ tauri info

Environment
  › OS: Mac OS 13.2.1 X64
  › Node.js: 18.9.0
  › npm: 8.19.1
  › pnpm: 7.24.2
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1 (outdated, latest: 1.2.3)
  › @tauri-apps/api [NPM]: 1.1.0 (outdated, latest: 1.2.0)
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: asset: mbtiles: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'; worker-src blob:
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ resources
  ├─ node_modules
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ build
  ├─ .git
  ├─ .idea
  └─ src

```

Disclaimer, I'm not familar with Rust & Tauri, so I'm not sure is that some steps missing and caused this.
Thanks in advance!
BTW, download and install the bundle App from the releases, it will quit once click on `add another mbtiles` as well

### Steps To Reproduce

1. Cloned this repo locally
2. pnpm install dependencice 
3. pnpm upgrade   // I think this is not the blame
4. install rust
5. pnpm dev // pnpm dev:web

### Expected behavior

When add another mbtiles, it should show the mbtiles.

### App Version

v1.6.0

### Operating System Version

macOS Ventura 13.2.1, M1 chip

**Comment by farfromrefug** [comment]
@pannz first you cant run `pnpm dev:web` it will fail because the code expects to be in a tauri environment.
Now for your error with `pnpm dev` which should work there might be something my app does not handle correctly with your mbtiles. Can you sahre it?

**Comment by pannz** [comment]
@farfromrefug thanks for looking into, `pnpm dev` not works as well on my side. 😭 
I download the [MB vector tiles openmaptiles 27M](https://download.bbbike.org/osm/bbbike/Singapore/Singapore.osm.mbtiles-openmaptiles.zip) at https://download.bbbike.org/osm/bbbike/Singapore/

**Comment by farfromrefug** [comment]
@pannz thanks i can reproduce the error with that file. Will fix it

**Comment by farfromrefug** [comment]
@pannz should be fixed now

**Comment by pannz** [comment]
Cool, fixed!
