### ISSUE TITLE
Shields in README links to https://github.com/kimlimjustin/xplorer/releases

### ISSUE THREAD

**Issue by Rodrigodd** [Akylas/mbview-rs#6]
Each shield in the README (the ones for Windows, Ubuntu, Arch Linux, and MacOS) links to the URL https://github.com/kimlimjustin/xplorer/releases. That is not what I would expect.

The "Download" and "Discussions" correctly links to the sections in this repository.

**Comment by farfromrefug** [comment]
@Rodrigodd thanks  a lot for the report. The readme is fixed

**Comment by Rodrigodd** [comment]
Thanks!
