### ISSUE TITLE
no more intel-based macOS support?

### ISSUE THREAD

**Issue by achou11** [Akylas/mbview-rs#7]
### Description

Prior to releases 1.7.1 and 1.7.2, there used to be a release artifact called `MBTilesViewer_x64.app.tar.gz` which contained the build to install the app for x86_64 macOS. however, with the recent releases, now's there's only a `MBTilesViewer_aarch64.app.tar.gz` artifact and the build it contains can only run on arm-based macOS.

Is the removal of intel arch intentional in these releases?

### Expected behavior

Have an artifact for installing the app on intel-based macOS devices.

### App Version

1.7.0

### Operating System Version

2019 MacBook Pro, macOS 14.5 (Sonoma), 2.3 GHz 8-Core Intel Core i9

**Comment by farfromrefug** [comment]
@achou11 indeed i did not even see that. Must be a tauri change. Will fix that

**Comment by farfromrefug** [comment]
@achou11 i updated the latest release. I now has the intel macos version https://github.com/Akylas/mbview-rs/releases/tag/v

**Comment by achou11** [comment]
awesome! was able to install so will close this. thanks!
